name: Build M3O CLI
on:
  repository_dispatch:
    types: [build_publish_cli]

jobs:
  generate:
    name: build M3O CLI
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
        id: go
      
      - name: Install Protoc
        uses: arduino/setup-protoc@master
      
      - name: Check GWT-m3o repo
        uses: actions/checkout@v2
        with:
          repository: 'GWT-M3O-TEST/GWT-m3o'
          path: m3o

      - name: Check GWT-services repo
        uses: actions/checkout@v2
        with:
          repository: 'GWT-M3O-TEST/GWT-services'
          path: services

      - name: Check micro repo
        uses: actions/checkout@v2
        with:
          repository: 'micro/micro'
          path: 'micro'
          ref: 'master'
      
      - name: Check GWT-m3o-cli repo
        uses: actions/checkout@v2
        with:
          repository: 'GWT-M3O-TEST/GWT-m3o-cli'
          path: m3o-cli
      
      - name: Enable caching
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install protoc gen micro plugin
        working-directory: micro/cmd/protoc-gen-micro
        run: |
          go get -u github.com/golang/protobuf/protoc-gen-go
          go install
      
      - name: Install openapi plugin
        working-directory: m3o/cmd/protoc-gen-openapi
        run: |
          go install

      - name: Install generator
        working-directory: m3o
        run: |
          # build the client generator
          pwd
          cd cmd/client-gen;
          go install
          cd ../../
          # delete existing cmd directory
          rm -rf ../services/cmd
          # copy our command directory in
          cp -r cmd ../services/
      
      - name: Generate M3O CLI
        working-directory: services
        if: github.ref == 'refs/heads/main'
        run: |
          rm -rf clients examples
          client-gen cli

      - name: Adjust generated things before pushing
        working-directory: services
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta'
        run: |
          # sync the examples to m3o-dart/example
          rsync -avz examples/cli/* ../m3o-cli/example/
      
      - name: house cleaning remove unnecessary files/folders
        working-directory: m3o-dart
        run: |
          # rm -rf .dart_tool .git .gitignore .packages pubspec.lock
      
      # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Push M3O CLI examples
        uses: dmnemec/copy_file_to_another_repo_action@main
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta'
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'm3o-cli/example/'
          destination_repo: 'GWT-M3O-TEST/GWT-m3o-cli'
          destination_branch: ${{ steps.extract_branch.outputs.branch }}
          destination_folder: 'example/'
          git_server: 'github.com'
          user_email:  'danieljoudat@gmail.com'
          user_name: 'lambdaR'
          use_rsync: true
          commit_message: 'Commit from GWT-M3O-TEST/GWT-m3o action'