name: Build M3O CLI
on:
  repository_dispatch:
    types: [build_publish_cli]

jobs:
  generate:
    name: build M3O CLI
    runs-on: ubuntu-latest
    steps:
      - name: Check GWT-m3o-cli repo
        uses: actions/checkout@v2
        with:
          path: m3o-cli
        
      - name: Check micro/services repo
        uses: actions/checkout@v2
        with:
          repository: 'micro/services'
          path: services

      - name: Generate m3o-cli clients
        uses: GWT-M3O-TEST/m3o-generator-action@v0.1.5
        with:
          target: 'cli'
          services_path: services

      - name: Adjust generated things before pushing
        working-directory: services 
        run: |
          # sync the examples to m3o-cli/examples
          rsync -avz examples/cli/* ../m3o-cli/examples/
      
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          cwd: m3o-cli
          message: Push to M3O-Cli repo
          pathspec_error_handling: exitImmediately