name: Build M3O CLI
on:
  repository_dispatch:
    types: [build_publish_cli]

jobs:
  generate:
    name: build M3O CLI
    runs-on: ubuntu-latest
    steps:
      - name: Check GWT-m3o-cli repo
        uses: actions/checkout@v2
        
      - name: Check micro/services repo
        uses: actions/checkout@v2
        with:
          repository: 'micro/services'
          path: services

      - name: Generate m3o-cli clients
        uses: GWT-M3O-TEST/m3o-generator-action@v0.1.3
        with:
          target: 'cli'
          services_path: services

      - name: Adjust generated things before pushing
        # working-directory: services
       
        run: |
          # sync the examples to m3o-cli/examples
          rsync -avz /github/workspace/services/examples/cli/* /github/workspace/m3o-cli/examples/
      
      - name: house cleaning remove unnecessary files/folders
        working-directory: m3o-cli
        run: |
          # rm -rf .git .gitignore
      
      # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Push M3O CLI examples
        uses: dmnemec/copy_file_to_another_repo_action@main
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/beta'
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'm3o-cli/examples/'
          destination_repo: 'GWT-M3O-TEST/GWT-m3o-cli'
          destination_branch: ${{ steps.extract_branch.outputs.branch }}
          destination_folder: 'examples/'
          git_server: 'github.com'
          user_email:  'danieljoudat@gmail.com'
          user_name: 'lambdaR'
          use_rsync: true
          commit_message: 'Commit from GWT-M3O-TEST/GWT-m3o action'